version: '3'
services:
  zookeeper-ovd:
    image: confluentinc/cp-zookeeper:6.0.1
    hostname: zookeeper-ovd
    container_name: zookeeper-ovd
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-ovd:
    image: confluentinc/cp-kafka:latest
    hostname: kafka-ovd
    container_name: kafka-ovd
    depends_on:
      - zookeeper-ovd
    ports:
      - "32000:32000"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper-ovd:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-ovd:9092,PLAINTEXT_HOST://localhost:32000
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka-ovd:9092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper-ovd:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'false'

  connect-ovd:
    image: streamthoughts/kafka-connect-file-pulse:2.3.0
    container_name: connect-ovd
    depends_on:
      - kafka-ovd
    ports:
      - "8083:8083"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'kafka-ovd:9092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect-ovd
      CONNECT_REST_PORT: 8083
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_ZOOKEEPER_CONNECT: 'zookeeper-ovd:2181'
      CONNECT_PLUGIN_PATH: "/usr/share/java,/usr/share/confluent-hub-components/"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
    volumes:
      - c:/dev/tmp/data:/var/share/kafka
    
  
  kafka-ui-ovd:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-ovd
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-ovd:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-ovd:2181
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: connect-ovd
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: 'http://connect-ovd:8083'
    ports:
      - 8500:8080